/*
auto-generated by: https://github.com/react-spring/gltfjsx
*/

import * as THREE from 'three'
import React, { useEffect, useRef } from 'react'
import { useLoader, useFrame } from 'react-three-fiber'
import { GLTFLoader } from 'three/examples/jsm/loaders/GLTFLoader'
import { DRACOLoader } from 'three/examples/jsm/loaders/DRACOLoader'

export default function Eggg(props) {
  const group = useRef()
  const { nodes, materials, animations } = useLoader(GLTFLoader, '/egg-thick.glb', loader => {
    const dracoLoader = new DRACOLoader()
    dracoLoader.setDecoderPath('/draco-gltf/')
    loader.setDRACOLoader(dracoLoader)
  })

  return (
    <group ref={group} {...props} dispose={null}>
      <primitive object={nodes.CINEMA_4D_Editor} />
      <group position={[0.09, 0.44, -0.25]} rotation={[-Math.PI / 2, 0, 0]}>
        <mesh material={materials.Mat} geometry={nodes.Cube_fracturepart1_0.geometry} />
        <mesh material={materials['Mat.1']} geometry={nodes.Cube_fracturepart1_1.geometry} />
      </group>
      <group position={[-0.14, 0.83, 0.23]} rotation={[-Math.PI / 2, 0, 0]}>
        <mesh material={materials.Mat} geometry={nodes.Cube_fracturepart2_0.geometry} />
        <mesh material={materials['Mat.1']} geometry={nodes.Cube_fracturepart2_1.geometry} />
      </group>
      <group position={[-0.19, 0.85, 0.03]} rotation={[-Math.PI / 2, 0, 0]}>
        <mesh material={materials.Mat} geometry={nodes.Cube_fracturepart3_0.geometry} />
        <mesh material={materials['Mat.1']} geometry={nodes.Cube_fracturepart3_1.geometry} />
      </group>
      <group position={[0.1, 0.96, 0.12]} rotation={[-Math.PI / 2, 0, 0]}>
        <mesh material={materials.Mat} geometry={nodes.Cube_fracturepart4_0.geometry} />
        <mesh material={materials['Mat.1']} geometry={nodes.Cube_fracturepart4_1.geometry} />
      </group>
      <group position={[-0.09, 0.98, 0.07]} rotation={[-Math.PI / 2, 0, 0]}>
        <mesh material={materials.Mat} geometry={nodes.Cube_fracturepart5_0.geometry} />
        <mesh material={materials['Mat.1']} geometry={nodes.Cube_fracturepart5_1.geometry} />
      </group>
      <group position={[0.15, 0.59, -0.25]} rotation={[-Math.PI / 2, 0, 0]}>
        <mesh material={materials.Mat} geometry={nodes.Cube_fracturepart7_0.geometry} />
        <mesh material={materials['Mat.1']} geometry={nodes.Cube_fracturepart7_1.geometry} />
      </group>
      <group position={[0.01, 0.55, -0.27]} rotation={[-Math.PI / 2, 0, 0]}>
        <mesh material={materials.Mat} geometry={nodes.Cube_fracturepart8_0.geometry} />
        <mesh material={materials['Mat.1']} geometry={nodes.Cube_fracturepart8_1.geometry} />
      </group>
      <group position={[-0.18, 0.38, -0.15]} rotation={[-Math.PI / 2, 0, 0]}>
        <mesh material={materials.Mat} geometry={nodes.Cube_fracturepart11_0.geometry} />
        <mesh material={materials['Mat.1']} geometry={nodes.Cube_fracturepart11_1.geometry} />
      </group>
      <group position={[-0.1, 0.65, 0.3]} rotation={[-Math.PI / 2, 0, 0]}>
        <mesh material={materials.Mat} geometry={nodes.Cube_fracturepart12_0.geometry} />
        <mesh material={materials['Mat.1']} geometry={nodes.Cube_fracturepart12_1.geometry} />
      </group>
      <group position={[-0.07, 0.85, -0.12]} rotation={[-Math.PI / 2, 0, 0]}>
        <mesh material={materials.Mat} geometry={nodes.Cube_fracturepart13_0.geometry} />
        <mesh material={materials['Mat.1']} geometry={nodes.Cube_fracturepart13_1.geometry} />
      </group>
      <group position={[-0.18, 0.65, 0.21]} rotation={[-Math.PI / 2, 0, 0]}>
        <mesh material={materials.Mat} geometry={nodes.Cube_fracturepart15_0.geometry} />
        <mesh material={materials['Mat.1']} geometry={nodes.Cube_fracturepart15_1.geometry} />
      </group>
      <group position={[0.02, 1, 0.11]} rotation={[-Math.PI / 2, 0, 0]}>
        <mesh material={materials.Mat} geometry={nodes.Cube_fracturepart18_0.geometry} />
        <mesh material={materials['Mat.1']} geometry={nodes.Cube_fracturepart18_1.geometry} />
      </group>
      <group position={[0.19, 0.92, 0.03]} rotation={[-Math.PI / 2, 0, 0]}>
        <mesh material={materials.Mat} geometry={nodes.Cube_fracturepart19_0.geometry} />
        <mesh material={materials['Mat.1']} geometry={nodes.Cube_fracturepart19_1.geometry} />
      </group>
      <group position={[-0.17, 0.82, -0.17]} rotation={[-Math.PI / 2, 0, 0]}>
        <mesh material={materials.Mat} geometry={nodes.Cube_fracturepart20_0.geometry} />
        <mesh material={materials['Mat.1']} geometry={nodes.Cube_fracturepart20_1.geometry} />
      </group>
      <group position={[-0.06, 0.91, 0.15]} rotation={[-Math.PI / 2, 0, 0]}>
        <mesh material={materials.Mat} geometry={nodes.Cube_fracturepart21_0.geometry} />
        <mesh material={materials['Mat.1']} geometry={nodes.Cube_fracturepart21_1.geometry} />
      </group>
      <group position={[0.08, 0.91, 0.11]} rotation={[-Math.PI / 2, 0, 0]}>
        <mesh material={materials.Mat} geometry={nodes.Cube_fracturepart22_0.geometry} />
        <mesh material={materials['Mat.1']} geometry={nodes.Cube_fracturepart22_1.geometry} />
      </group>
      <group position={[0.16, 0.66, -0.22]} rotation={[-Math.PI / 2, 0, 0]}>
        <mesh material={materials.Mat} geometry={nodes.Cube_fracturepart23_0.geometry} />
        <mesh material={materials['Mat.1']} geometry={nodes.Cube_fracturepart23_1.geometry} />
      </group>
      <group position={[0, 0.8, -0.23]} rotation={[-Math.PI / 2, 0, 0]}>
        <mesh material={materials.Mat} geometry={nodes.Cube_fracturepart24_0.geometry} />
        <mesh material={materials['Mat.1']} geometry={nodes.Cube_fracturepart24_1.geometry} />
      </group>
      <group position={[-0.24, 0.86, 0.03]} rotation={[-Math.PI / 2, 0, 0]}>
        <mesh material={materials.Mat} geometry={nodes.Cube_fracturepart26_0.geometry} />
        <mesh material={materials['Mat.1']} geometry={nodes.Cube_fracturepart26_1.geometry} />
      </group>
      <group position={[0.11, 0.89, -0.02]} rotation={[-Math.PI / 2, 0, 0]}>
        <mesh material={materials.Mat} geometry={nodes.Cube_fracturepart27_0.geometry} />
        <mesh material={materials['Mat.1']} geometry={nodes.Cube_fracturepart27_1.geometry} />
      </group>
      <group position={[0.08, 0.95, -0.05]} rotation={[-Math.PI / 2, 0, 0]}>
        <mesh material={materials.Mat} geometry={nodes.Cube_fracturepart28_0.geometry} />
        <mesh material={materials['Mat.1']} geometry={nodes.Cube_fracturepart28_1.geometry} />
      </group>
      <group position={[0.18, 0.93, 0.11]} rotation={[-Math.PI / 2, 0, 0]}>
        <mesh material={materials.Mat} geometry={nodes.Cube_fracturepart29_0.geometry} />
        <mesh material={materials['Mat.1']} geometry={nodes.Cube_fracturepart29_1.geometry} />
      </group>
      <group position={[-0.15, 0.24, 0.03]} rotation={[-Math.PI / 2, 0, 0]}>
        <mesh material={materials.Mat} geometry={nodes.Cube_fracturepart30_0.geometry} />
        <mesh material={materials['Mat.1']} geometry={nodes.Cube_fracturepart30_1.geometry} />
      </group>
      <group position={[0.07, 0.92, -0.14]} rotation={[-Math.PI / 2, 0, 0]}>
        <mesh material={materials.Mat} geometry={nodes.Cube_fracturepart31_0.geometry} />
        <mesh material={materials['Mat.1']} geometry={nodes.Cube_fracturepart31_1.geometry} />
      </group>
      <group position={[0.18, 0.43, 0.28]} rotation={[-Math.PI / 2, 0, 0]}>
        <mesh material={materials.Mat} geometry={nodes.Cube_fracturepart32_0.geometry} />
        <mesh material={materials['Mat.1']} geometry={nodes.Cube_fracturepart32_1.geometry} />
      </group>
      <group position={[0.22, 0.73, -0.03]} rotation={[-Math.PI / 2, 0, 0]}>
        <mesh material={materials.Mat} geometry={nodes.Cube_fracturepart33_0.geometry} />
        <mesh material={materials['Mat.1']} geometry={nodes.Cube_fracturepart33_1.geometry} />
      </group>
      <group position={[-0.14, 0.95, -0.06]} rotation={[-Math.PI / 2, 0, 0]}>
        <mesh material={materials.Mat} geometry={nodes.Cube_fracturepart34_0.geometry} />
        <mesh material={materials['Mat.1']} geometry={nodes.Cube_fracturepart34_1.geometry} />
      </group>
      <group position={[-0.06, 0.83, -0.18]} rotation={[-Math.PI / 2, 0, 0]}>
        <mesh material={materials.Mat} geometry={nodes.Cube_fracturepart35_0.geometry} />
        <mesh material={materials['Mat.1']} geometry={nodes.Cube_fracturepart35_1.geometry} />
      </group>
      <group position={[-0.27, 0.79, 0.05]} rotation={[-Math.PI / 2, 0, 0]}>
        <mesh material={materials.Mat} geometry={nodes.Cube_fracturepart36_0.geometry} />
        <mesh material={materials['Mat.1']} geometry={nodes.Cube_fracturepart36_1.geometry} />
      </group>
      <group position={[0.19, 0.79, -0.04]} rotation={[-Math.PI / 2, 0, 0]}>
        <mesh material={materials.Mat} geometry={nodes.Cube_fracturepart37_0.geometry} />
        <mesh material={materials['Mat.1']} geometry={nodes.Cube_fracturepart37_1.geometry} />
      </group>
      <group position={[0.06, 0.92, 0.06]} rotation={[-Math.PI / 2, 0, 0]}>
        <mesh material={materials.Mat} geometry={nodes.Cube_fracturepart38_0.geometry} />
        <mesh material={materials['Mat.1']} geometry={nodes.Cube_fracturepart38_1.geometry} />
      </group>
      <group position={[-0.11, 0.54, 0.27]} rotation={[-Math.PI / 2, 0, 0]}>
        <mesh material={materials.Mat} geometry={nodes.Cube_fracturepart39_0.geometry} />
        <mesh material={materials['Mat.1']} geometry={nodes.Cube_fracturepart39_1.geometry} />
      </group>
      <group position={[-0.17, 0.73, 0.22]} rotation={[-Math.PI / 2, 0, 0]}>
        <mesh material={materials.Mat} geometry={nodes.Cube_fracturepart40_0.geometry} />
        <mesh material={materials['Mat.1']} geometry={nodes.Cube_fracturepart40_1.geometry} />
      </group>
      <group position={[-0.26, 0.44, 0.1]} rotation={[-Math.PI / 2, 0, 0]}>
        <mesh material={materials.Mat} geometry={nodes.Cube_fracturepart41_0.geometry} />
        <mesh material={materials['Mat.1']} geometry={nodes.Cube_fracturepart41_1.geometry} />
      </group>
      <group position={[-0.01, 0.96, 0.15]} rotation={[-Math.PI / 2, 0, 0]}>
        <mesh material={materials.Mat} geometry={nodes.Cube_fracturepart42_0.geometry} />
        <mesh material={materials['Mat.1']} geometry={nodes.Cube_fracturepart42_1.geometry} />
      </group>
      <group position={[-0.02, 0.36, -0.2]} rotation={[-Math.PI / 2, 0, 0]}>
        <mesh material={materials.Mat} geometry={nodes.Cube_fracturepart43_0.geometry} />
        <mesh material={materials['Mat.1']} geometry={nodes.Cube_fracturepart43_1.geometry} />
      </group>
      <group position={[0.09, 0.97, 0.01]} rotation={[-Math.PI / 2, 0, 0]}>
        <mesh material={materials.Mat} geometry={nodes.Cube_fracturepart44_0.geometry} />
        <mesh material={materials['Mat.1']} geometry={nodes.Cube_fracturepart44_1.geometry} />
      </group>
      <group position={[-0.21, 0.64, -0.19]} rotation={[-Math.PI / 2, 0, 0]}>
        <mesh material={materials.Mat} geometry={nodes.Cube_fracturepart45_0.geometry} />
        <mesh material={materials['Mat.1']} geometry={nodes.Cube_fracturepart45_1.geometry} />
      </group>
      <group position={[0.25, 0.49, 0.18]} rotation={[-Math.PI / 2, 0, 0]}>
        <mesh material={materials.Mat} geometry={nodes.Cube_fracturepart46_0.geometry} />
        <mesh material={materials['Mat.1']} geometry={nodes.Cube_fracturepart46_1.geometry} />
      </group>
      <group position={[-0.03, 0.72, -0.23]} rotation={[-Math.PI / 2, 0, 0]}>
        <mesh material={materials.Mat} geometry={nodes.Cube_fracturepart47_0.geometry} />
        <mesh material={materials['Mat.1']} geometry={nodes.Cube_fracturepart47_1.geometry} />
      </group>
      <group position={[0.13, 0.78, -0.13]} rotation={[-Math.PI / 2, 0, 0]}>
        <mesh material={materials.Mat} geometry={nodes.Cube_fracturepart48_0.geometry} />
        <mesh material={materials['Mat.1']} geometry={nodes.Cube_fracturepart48_1.geometry} />
      </group>
      <group position={[0.14, 0.84, -0.05]} rotation={[-Math.PI / 2, 0, 0]}>
        <mesh material={materials.Mat} geometry={nodes.Cube_fracturepart49_0.geometry} />
        <mesh material={materials['Mat.1']} geometry={nodes.Cube_fracturepart49_1.geometry} />
      </group>
      <group position={[-0.23, 0.54, 0.25]} rotation={[-Math.PI / 2, 0, 0]}>
        <mesh material={materials.Mat} geometry={nodes.Cube_fracturepart50_0.geometry} />
        <mesh material={materials['Mat.1']} geometry={nodes.Cube_fracturepart50_1.geometry} />
      </group>
      <group position={[0.02, 0.84, -0.15]} rotation={[-Math.PI / 2, 0, 0]}>
        <mesh material={materials.Mat} geometry={nodes.Cube_fracturepart52_0.geometry} />
        <mesh material={materials['Mat.1']} geometry={nodes.Cube_fracturepart52_1.geometry} />
      </group>
      <group position={[-0.03, 0.7, 0.27]} rotation={[-Math.PI / 2, 0, 0]}>
        <mesh material={materials.Mat} geometry={nodes.Cube_fracturepart53_0.geometry} />
        <mesh material={materials['Mat.1']} geometry={nodes.Cube_fracturepart53_1.geometry} />
      </group>
      <mesh
        material={materials['Mat.1']}
        geometry={nodes.Cube_fracturepart54.geometry}
        position={[0, 0.97, 0.1]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <group position={[-0.24, 0.78, -0.05]} rotation={[-Math.PI / 2, 0, 0]}>
        <mesh material={materials.Mat} geometry={nodes.Cube_fracturepart55_0.geometry} />
        <mesh material={materials['Mat.1']} geometry={nodes.Cube_fracturepart55_1.geometry} />
      </group>
      <group position={[-0.03, 1.01, 0]} rotation={[-Math.PI / 2, 0, 0]}>
        <mesh material={materials.Mat} geometry={nodes.Cube_fracturepart56_0.geometry} />
        <mesh material={materials['Mat.1']} geometry={nodes.Cube_fracturepart56_1.geometry} />
      </group>
      <group position={[-0.22, 0.51, 0.21]} rotation={[-Math.PI / 2, 0, 0]}>
        <mesh material={materials.Mat} geometry={nodes.Cube_fracturepart57_0.geometry} />
        <mesh material={materials['Mat.1']} geometry={nodes.Cube_fracturepart57_1.geometry} />
      </group>
      <group position={[-0.03, 0.85, 0.22]} rotation={[-Math.PI / 2, 0, 0]}>
        <mesh material={materials.Mat} geometry={nodes.Cube_fracturepart58_0.geometry} />
        <mesh material={materials['Mat.1']} geometry={nodes.Cube_fracturepart58_1.geometry} />
      </group>
      <group position={[0.11, 0.66, 0.31]} rotation={[-Math.PI / 2, 0, 0]}>
        <mesh material={materials.Mat} geometry={nodes.Cube_fracturepart59_0.geometry} />
        <mesh material={materials['Mat.1']} geometry={nodes.Cube_fracturepart59_1.geometry} />
      </group>
      <group position={[0.18, 0.89, 0.1]} rotation={[-Math.PI / 2, 0, 0]}>
        <mesh material={materials.Mat} geometry={nodes.Cube_fracturepart60_0.geometry} />
        <mesh material={materials['Mat.1']} geometry={nodes.Cube_fracturepart60_1.geometry} />
      </group>
      <group position={[-0.08, 0.98, 0.15]} rotation={[-Math.PI / 2, 0, 0]}>
        <mesh material={materials.Mat} geometry={nodes.Cube_fracturepart62_0.geometry} />
        <mesh material={materials['Mat.1']} geometry={nodes.Cube_fracturepart62_1.geometry} />
      </group>
      <group position={[-0.2, 0.74, 0.07]} rotation={[-Math.PI / 2, 0, 0]}>
        <mesh material={materials.Mat} geometry={nodes.Cube_fracturepart63_0.geometry} />
        <mesh material={materials['Mat.1']} geometry={nodes.Cube_fracturepart63_1.geometry} />
      </group>
      <group position={[-0.26, 0.66, 0.16]} rotation={[-Math.PI / 2, 0, 0]}>
        <mesh material={materials.Mat} geometry={nodes.Cube_fracturepart65_0.geometry} />
        <mesh material={materials['Mat.1']} geometry={nodes.Cube_fracturepart65_1.geometry} />
      </group>
      <group position={[-0.05, 0.67, 0.34]} rotation={[-Math.PI / 2, 0, 0]}>
        <mesh material={materials.Mat} geometry={nodes.Cube_fracturepart66_0.geometry} />
        <mesh material={materials['Mat.1']} geometry={nodes.Cube_fracturepart66_1.geometry} />
      </group>
      <group position={[0.13, 0.85, 0.12]} rotation={[-Math.PI / 2, 0, 0]}>
        <mesh material={materials.Mat} geometry={nodes.Cube_fracturepart67_0.geometry} />
        <mesh material={materials['Mat.1']} geometry={nodes.Cube_fracturepart67_1.geometry} />
      </group>
      <group position={[-0.23, 0.57, 0.15]} rotation={[-Math.PI / 2, 0, 0]}>
        <mesh material={materials.Mat} geometry={nodes.Cube_fracturepart68_0.geometry} />
        <mesh material={materials['Mat.1']} geometry={nodes.Cube_fracturepart68_1.geometry} />
      </group>
      <group position={[-0.07, 0.9, -0.09]} rotation={[-Math.PI / 2, 0, 0]}>
        <mesh material={materials.Mat} geometry={nodes.Cube_fracturepart69_0.geometry} />
        <mesh material={materials['Mat.1']} geometry={nodes.Cube_fracturepart69_1.geometry} />
      </group>
      <group position={[0.02, 0.9, -0.09]} rotation={[-Math.PI / 2, 0, 0]}>
        <mesh material={materials.Mat} geometry={nodes.Cube_fracturepart70_0.geometry} />
        <mesh material={materials['Mat.1']} geometry={nodes.Cube_fracturepart70_1.geometry} />
      </group>
      <group position={[0.14, 0.92, 0.16]} rotation={[-Math.PI / 2, 0, 0]}>
        <mesh material={materials.Mat} geometry={nodes.Cube_fracturepart71_0.geometry} />
        <mesh material={materials['Mat.1']} geometry={nodes.Cube_fracturepart71_1.geometry} />
      </group>
      <group position={[0.08, 0.21, 0.11]} rotation={[-Math.PI / 2, 0, 0]}>
        <mesh material={materials.Mat} geometry={nodes.Cube_fracturepart72_0.geometry} />
        <mesh material={materials['Mat.1']} geometry={nodes.Cube_fracturepart72_1.geometry} />
      </group>
      <group position={[-0.19, 0.89, 0.12]} rotation={[-Math.PI / 2, 0, 0]}>
        <mesh material={materials.Mat} geometry={nodes.Cube_fracturepart73_0.geometry} />
        <mesh material={materials['Mat.1']} geometry={nodes.Cube_fracturepart73_1.geometry} />
      </group>
      <group position={[0.02, 0.87, -0.21]} rotation={[-Math.PI / 2, 0, 0]}>
        <mesh material={materials.Mat} geometry={nodes.Cube_fracturepart74_0.geometry} />
        <mesh material={materials['Mat.1']} geometry={nodes.Cube_fracturepart74_1.geometry} />
      </group>
      <group position={[0.14, 0.34, -0.06]} rotation={[-Math.PI / 2, 0, 0]}>
        <mesh material={materials.Mat} geometry={nodes.Cube_fracturepart75_0.geometry} />
        <mesh material={materials['Mat.1']} geometry={nodes.Cube_fracturepart75_1.geometry} />
      </group>
      <group position={[-0.05, 0.48, -0.24]} rotation={[-Math.PI / 2, 0, 0]}>
        <mesh material={materials.Mat} geometry={nodes.Cube_fracturepart76_0.geometry} />
        <mesh material={materials['Mat.1']} geometry={nodes.Cube_fracturepart76_1.geometry} />
      </group>
      <group position={[0.21, 0.66, 0.26]} rotation={[-Math.PI / 2, 0, 0]}>
        <mesh material={materials.Mat} geometry={nodes.Cube_fracturepart78_0.geometry} />
        <mesh material={materials['Mat.1']} geometry={nodes.Cube_fracturepart78_1.geometry} />
      </group>
      <group position={[0.18, 0.48, -0.21]} rotation={[-Math.PI / 2, 0, 0]}>
        <mesh material={materials.Mat} geometry={nodes.Cube_fracturepart79_0.geometry} />
        <mesh material={materials['Mat.1']} geometry={nodes.Cube_fracturepart79_1.geometry} />
      </group>
      <group position={[-0.03, 0.98, 0.11]} rotation={[-Math.PI / 2, 0, 0]}>
        <mesh material={materials.Mat} geometry={nodes.Cube_fracturepart80_0.geometry} />
        <mesh material={materials['Mat.1']} geometry={nodes.Cube_fracturepart80_1.geometry} />
      </group>
      <group position={[0.14, 0.83, -0.21]} rotation={[-Math.PI / 2, 0, 0]}>
        <mesh material={materials.Mat} geometry={nodes.Cube_fracturepart81_0.geometry} />
        <mesh material={materials['Mat.1']} geometry={nodes.Cube_fracturepart81_1.geometry} />
      </group>
      <group position={[-0.09, 0.96, -0.07]} rotation={[-Math.PI / 2, 0, 0]}>
        <mesh material={materials.Mat} geometry={nodes.Cube_fracturepart82_0.geometry} />
        <mesh material={materials['Mat.1']} geometry={nodes.Cube_fracturepart82_1.geometry} />
      </group>
      <group position={[-0.23, 0.76, 0.05]} rotation={[-Math.PI / 2, 0, 0]}>
        <mesh material={materials.Mat} geometry={nodes.Cube_fracturepart83_0.geometry} />
        <mesh material={materials['Mat.1']} geometry={nodes.Cube_fracturepart83_1.geometry} />
      </group>
      <group position={[0.23, 0.54, -0.14]} rotation={[-Math.PI / 2, 0, 0]}>
        <mesh material={materials.Mat} geometry={nodes.Cube_fracturepart84_0.geometry} />
        <mesh material={materials['Mat.1']} geometry={nodes.Cube_fracturepart84_1.geometry} />
      </group>
      <group position={[-0.07, 0.84, 0.16]} rotation={[-Math.PI / 2, 0, 0]}>
        <mesh material={materials.Mat} geometry={nodes.Cube_fracturepart85_0.geometry} />
        <mesh material={materials['Mat.1']} geometry={nodes.Cube_fracturepart85_1.geometry} />
      </group>
      <group position={[-0.05, 0.86, 0.27]} rotation={[-Math.PI / 2, 0, 0]}>
        <mesh material={materials.Mat} geometry={nodes.Cube_fracturepart86_0.geometry} />
        <mesh material={materials['Mat.1']} geometry={nodes.Cube_fracturepart86_1.geometry} />
      </group>
      <group position={[0.23, 0.82, 0.15]} rotation={[-Math.PI / 2, 0, 0]}>
        <mesh material={materials.Mat} geometry={nodes.Cube_fracturepart87_0.geometry} />
        <mesh material={materials['Mat.1']} geometry={nodes.Cube_fracturepart87_1.geometry} />
      </group>
      <group position={[0.07, 0.9, 0.17]} rotation={[-Math.PI / 2, 0, 0]}>
        <mesh material={materials.Mat} geometry={nodes.Cube_fracturepart88_0.geometry} />
        <mesh material={materials['Mat.1']} geometry={nodes.Cube_fracturepart88_1.geometry} />
      </group>
      <group position={[-0.29, 0.74, 0.03]} rotation={[-Math.PI / 2, 0, 0]}>
        <mesh material={materials.Mat} geometry={nodes.Cube_fracturepart90_0.geometry} />
        <mesh material={materials['Mat.1']} geometry={nodes.Cube_fracturepart90_1.geometry} />
      </group>
      <group position={[0.13, 0.96, 0.05]} rotation={[-Math.PI / 2, 0, 0]}>
        <mesh material={materials.Mat} geometry={nodes.Cube_fracturepart92_0.geometry} />
        <mesh material={materials['Mat.1']} geometry={nodes.Cube_fracturepart92_1.geometry} />
      </group>
      <group position={[0.1, 0.88, -0.09]} rotation={[-Math.PI / 2, 0, 0]}>
        <mesh material={materials.Mat} geometry={nodes.Cube_fracturepart93_0.geometry} />
        <mesh material={materials['Mat.1']} geometry={nodes.Cube_fracturepart93_1.geometry} />
      </group>
      <group position={[0.1, 0.69, -0.2]} rotation={[-Math.PI / 2, 0, 0]}>
        <mesh material={materials.Mat} geometry={nodes.Cube_fracturepart94_0.geometry} />
        <mesh material={materials['Mat.1']} geometry={nodes.Cube_fracturepart94_1.geometry} />
      </group>
      <group position={[-0.26, 0.53, -0.11]} rotation={[-Math.PI / 2, 0, 0]}>
        <mesh material={materials.Mat} geometry={nodes.Cube_fracturepart96_0.geometry} />
        <mesh material={materials['Mat.1']} geometry={nodes.Cube_fracturepart96_1.geometry} />
      </group>
      <group position={[0.25, 0.64, 0.18]} rotation={[-Math.PI / 2, 0, 0]}>
        <mesh material={materials.Mat} geometry={nodes.Cube_fracturepart97_0.geometry} />
        <mesh material={materials['Mat.1']} geometry={nodes.Cube_fracturepart97_1.geometry} />
      </group>
      <group position={[-0.1, 0.91, -0.16]} rotation={[-Math.PI / 2, 0, 0]}>
        <mesh material={materials.Mat} geometry={nodes.Cube_fracturepart98_0.geometry} />
        <mesh material={materials['Mat.1']} geometry={nodes.Cube_fracturepart98_1.geometry} />
      </group>
      <group position={[0.27, 0.58, -0.05]} rotation={[-Math.PI / 2, 0, 0]}>
        <mesh material={materials.Mat} geometry={nodes.Cube_fracturepart99_0.geometry} />
        <mesh material={materials['Mat.1']} geometry={nodes.Cube_fracturepart99_1.geometry} />
      </group>
      <group position={[0.11, 0.95, 0.09]} rotation={[-Math.PI / 2, 0, 0]}>
        <mesh material={materials.Mat} geometry={nodes.Cube_fracturepart100_0.geometry} />
        <mesh material={materials['Mat.1']} geometry={nodes.Cube_fracturepart100_1.geometry} />
      </group>
      <group position={[0, 0.98, -0.07]} rotation={[-Math.PI / 2, 0, 0]}>
        <mesh material={materials.Mat} geometry={nodes.Cube_fracturepart101_0.geometry} />
        <mesh material={materials['Mat.1']} geometry={nodes.Cube_fracturepart101_1.geometry} />
      </group>
      <group position={[0.02, 0.94, 0.09]} rotation={[-Math.PI / 2, 0, 0]}>
        <mesh material={materials.Mat} geometry={nodes.Cube_fracturepart102_0.geometry} />
        <mesh material={materials['Mat.1']} geometry={nodes.Cube_fracturepart102_1.geometry} />
      </group>
      <group position={[0.04, 0.98, -0.04]} rotation={[-Math.PI / 2, 0, 0]}>
        <mesh material={materials.Mat} geometry={nodes.Cube_fracturepart103_0.geometry} />
        <mesh material={materials['Mat.1']} geometry={nodes.Cube_fracturepart103_1.geometry} />
      </group>
      <group position={[0.23, 0.75, -0.16]} rotation={[-Math.PI / 2, 0, 0]}>
        <mesh material={materials.Mat} geometry={nodes.Cube_fracturepart104_0.geometry} />
        <mesh material={materials['Mat.1']} geometry={nodes.Cube_fracturepart104_1.geometry} />
      </group>
      <group position={[-0.06, 0.95, -0.03]} rotation={[-Math.PI / 2, 0, 0]}>
        <mesh material={materials.Mat} geometry={nodes.Cube_fracturepart105_0.geometry} />
        <mesh material={materials['Mat.1']} geometry={nodes.Cube_fracturepart105_1.geometry} />
      </group>
      <group position={[0.2, 0.78, 0.14]} rotation={[-Math.PI / 2, 0, 0]}>
        <mesh material={materials.Mat} geometry={nodes.Cube_fracturepart106_0.geometry} />
        <mesh material={materials['Mat.1']} geometry={nodes.Cube_fracturepart106_1.geometry} />
      </group>
      <group position={[-0.15, 0.95, 0.02]} rotation={[-Math.PI / 2, 0, 0]}>
        <mesh material={materials.Mat} geometry={nodes.Cube_fracturepart107_0.geometry} />
        <mesh material={materials['Mat.1']} geometry={nodes.Cube_fracturepart107_1.geometry} />
      </group>
      <group position={[0.15, 0.86, -0.15]} rotation={[-Math.PI / 2, 0, 0]}>
        <mesh material={materials.Mat} geometry={nodes.Cube_fracturepart108_0.geometry} />
        <mesh material={materials['Mat.1']} geometry={nodes.Cube_fracturepart108_1.geometry} />
      </group>
      <group position={[0.06, 0.82, 0.27]} rotation={[-Math.PI / 2, 0, 0]}>
        <mesh material={materials.Mat} geometry={nodes.Cube_fracturepart109_0.geometry} />
        <mesh material={materials['Mat.1']} geometry={nodes.Cube_fracturepart109_1.geometry} />
      </group>
      <group position={[-0.27, 0.39, -0.13]} rotation={[-Math.PI / 2, 0, 0]}>
        <mesh material={materials.Mat} geometry={nodes.Cube_fracturepart110_0.geometry} />
        <mesh material={materials['Mat.1']} geometry={nodes.Cube_fracturepart110_1.geometry} />
      </group>
      <group position={[0.2, 0.81, 0.07]} rotation={[-Math.PI / 2, 0, 0]}>
        <mesh material={materials.Mat} geometry={nodes.Cube_fracturepart111_0.geometry} />
        <mesh material={materials['Mat.1']} geometry={nodes.Cube_fracturepart111_1.geometry} />
      </group>
      <group position={[0.23, 0.71, 0.05]} rotation={[-Math.PI / 2, 0, 0]}>
        <mesh material={materials.Mat} geometry={nodes.Cube_fracturepart112_0.geometry} />
        <mesh material={materials['Mat.1']} geometry={nodes.Cube_fracturepart112_1.geometry} />
      </group>
      <group position={[0.07, 0.96, 0.16]} rotation={[-Math.PI / 2, 0, 0]}>
        <mesh material={materials.Mat} geometry={nodes.Cube_fracturepart113_0.geometry} />
        <mesh material={materials['Mat.1']} geometry={nodes.Cube_fracturepart113_1.geometry} />
      </group>
      <group position={[-0.09, 0.98, -0.01]} rotation={[-Math.PI / 2, 0, 0]}>
        <mesh material={materials.Mat} geometry={nodes.Cube_fracturepart114_0.geometry} />
        <mesh material={materials['Mat.1']} geometry={nodes.Cube_fracturepart114_1.geometry} />
      </group>
      <group position={[0.05, 0.48, 0.32]} rotation={[-Math.PI / 2, 0, 0]}>
        <mesh material={materials.Mat} geometry={nodes.Cube_fracturepart117_0.geometry} />
        <mesh material={materials['Mat.1']} geometry={nodes.Cube_fracturepart117_1.geometry} />
      </group>
      <group position={[-0.24, 0.75, 0.18]} rotation={[-Math.PI / 2, 0, 0]}>
        <mesh material={materials.Mat} geometry={nodes.Cube_fracturepart118_0.geometry} />
        <mesh material={materials['Mat.1']} geometry={nodes.Cube_fracturepart118_1.geometry} />
      </group>
      <group position={[0.07, 0.98, 0.11]} rotation={[-Math.PI / 2, 0, 0]}>
        <mesh material={materials.Mat} geometry={nodes.Cube_fracturepart119_0.geometry} />
        <mesh material={materials['Mat.1']} geometry={nodes.Cube_fracturepart119_1.geometry} />
      </group>
      <group position={[-0.25, 0.67, 0.07]} rotation={[-Math.PI / 2, 0, 0]}>
        <mesh material={materials.Mat} geometry={nodes.Cube_fracturepart120_0.geometry} />
        <mesh material={materials['Mat.1']} geometry={nodes.Cube_fracturepart120_1.geometry} />
      </group>
      <group position={[0.09, 0.76, -0.23]} rotation={[-Math.PI / 2, 0, 0]}>
        <mesh material={materials.Mat} geometry={nodes.Cube_fracturepart121_0.geometry} />
        <mesh material={materials['Mat.1']} geometry={nodes.Cube_fracturepart121_1.geometry} />
      </group>
      <group position={[-0.06, 0.35, 0.3]} rotation={[-Math.PI / 2, 0, 0]}>
        <mesh material={materials.Mat} geometry={nodes.Cube_fracturepart122_0.geometry} />
        <mesh material={materials['Mat.1']} geometry={nodes.Cube_fracturepart122_1.geometry} />
      </group>
      <group position={[0.13, 0.88, 0.06]} rotation={[-Math.PI / 2, 0, 0]}>
        <mesh material={materials.Mat} geometry={nodes.Cube_fracturepart123_0.geometry} />
        <mesh material={materials['Mat.1']} geometry={nodes.Cube_fracturepart123_1.geometry} />
      </group>
      <group position={[-0.28, 0.68, 0.03]} rotation={[-Math.PI / 2, 0, 0]}>
        <mesh material={materials.Mat} geometry={nodes.Cube_fracturepart124_0.geometry} />
        <mesh material={materials['Mat.1']} geometry={nodes.Cube_fracturepart124_1.geometry} />
      </group>
      <group position={[-0.19, 0.73, -0.21]} rotation={[-Math.PI / 2, 0, 0]}>
        <mesh material={materials.Mat} geometry={nodes.Cube_fracturepart125_0.geometry} />
        <mesh material={materials['Mat.1']} geometry={nodes.Cube_fracturepart125_1.geometry} />
      </group>
      <group position={[-0.17, 0.87, -0.09]} rotation={[-Math.PI / 2, 0, 0]}>
        <mesh material={materials.Mat} geometry={nodes.Cube_fracturepart126_0.geometry} />
        <mesh material={materials['Mat.1']} geometry={nodes.Cube_fracturepart126_1.geometry} />
      </group>
      <group position={[0.29, 0.7, 0.02]} rotation={[-Math.PI / 2, 0, 0]}>
        <mesh material={materials.Mat} geometry={nodes.Cube_fracturepart127_0.geometry} />
        <mesh material={materials['Mat.1']} geometry={nodes.Cube_fracturepart127_1.geometry} />
      </group>
      <group position={[0.04, 0.85, 0.2]} rotation={[-Math.PI / 2, 0, 0]}>
        <mesh material={materials.Mat} geometry={nodes.Cube_fracturepart128_0.geometry} />
        <mesh material={materials['Mat.1']} geometry={nodes.Cube_fracturepart128_1.geometry} />
      </group>
      <group position={[0.03, 0.95, -0.01]} rotation={[-Math.PI / 2, 0, 0]}>
        <mesh material={materials.Mat} geometry={nodes.Cube_fracturepart129_0.geometry} />
        <mesh material={materials['Mat.1']} geometry={nodes.Cube_fracturepart129_1.geometry} />
      </group>
      <group position={[0.12, 0.56, 0.31]} rotation={[-Math.PI / 2, 0, 0]}>
        <mesh material={materials.Mat} geometry={nodes.Cube_fracturepart130_0.geometry} />
        <mesh material={materials['Mat.1']} geometry={nodes.Cube_fracturepart130_1.geometry} />
      </group>
      <group position={[-0.29, 0.44, -0.02]} rotation={[-Math.PI / 2, 0, 0]}>
        <mesh material={materials.Mat} geometry={nodes.Cube_fracturepart131_0.geometry} />
        <mesh material={materials['Mat.1']} geometry={nodes.Cube_fracturepart131_1.geometry} />
      </group>
      <group position={[-0.11, 0.85, -0.06]} rotation={[-Math.PI / 2, 0, 0]}>
        <mesh material={materials.Mat} geometry={nodes.Cube_fracturepart132_0.geometry} />
        <mesh material={materials['Mat.1']} geometry={nodes.Cube_fracturepart132_1.geometry} />
      </group>
      <group position={[-0.18, 0.85, 0.1]} rotation={[-Math.PI / 2, 0, 0]}>
        <mesh material={materials.Mat} geometry={nodes.Cube_fracturepart133_0.geometry} />
        <mesh material={materials['Mat.1']} geometry={nodes.Cube_fracturepart133_1.geometry} />
      </group>
      <group position={[-0.01, 0.97, 0.05]} rotation={[-Math.PI / 2, 0, 0]}>
        <mesh material={materials.Mat} geometry={nodes.Cube_fracturepart134_0.geometry} />
        <mesh material={materials['Mat.1']} geometry={nodes.Cube_fracturepart134_1.geometry} />
      </group>
      <group position={[0.27, 0.63, 0.01]} rotation={[-Math.PI / 2, 0, 0]}>
        <mesh material={materials.Mat} geometry={nodes.Cube_fracturepart135_0.geometry} />
        <mesh material={materials['Mat.1']} geometry={nodes.Cube_fracturepart135_1.geometry} />
      </group>
      <group position={[0.16, 0.8, 0.19]} rotation={[-Math.PI / 2, 0, 0]}>
        <mesh material={materials.Mat} geometry={nodes.Cube_fracturepart136_0.geometry} />
        <mesh material={materials['Mat.1']} geometry={nodes.Cube_fracturepart136_1.geometry} />
      </group>
      <group position={[0.03, 0.89, 0.17]} rotation={[-Math.PI / 2, 0, 0]}>
        <mesh material={materials.Mat} geometry={nodes.Cube_fracturepart137_0.geometry} />
        <mesh material={materials['Mat.1']} geometry={nodes.Cube_fracturepart137_1.geometry} />
      </group>
      <group position={[0.03, 0.86, -0.13]} rotation={[-Math.PI / 2, 0, 0]}>
        <mesh material={materials.Mat} geometry={nodes.Cube_fracturepart138_0.geometry} />
        <mesh material={materials['Mat.1']} geometry={nodes.Cube_fracturepart138_1.geometry} />
      </group>
      <group position={[-0.23, 0.78, 0.15]} rotation={[-Math.PI / 2, 0, 0]}>
        <mesh material={materials.Mat} geometry={nodes.Cube_fracturepart139_0.geometry} />
        <mesh material={materials['Mat.1']} geometry={nodes.Cube_fracturepart139_1.geometry} />
      </group>
      <group position={[-0.27, 0.44, 0.18]} rotation={[-Math.PI / 2, 0, 0]}>
        <mesh material={materials.Mat} geometry={nodes.Cube_fracturepart140_0.geometry} />
        <mesh material={materials['Mat.1']} geometry={nodes.Cube_fracturepart140_1.geometry} />
      </group>
      <group position={[-0.24, 0.78, -0.14]} rotation={[-Math.PI / 2, 0, 0]}>
        <mesh material={materials.Mat} geometry={nodes.Cube_fracturepart142_0.geometry} />
        <mesh material={materials['Mat.1']} geometry={nodes.Cube_fracturepart142_1.geometry} />
      </group>
      <group position={[0.07, 0.86, -0.14]} rotation={[-Math.PI / 2, 0, 0]}>
        <mesh material={materials.Mat} geometry={nodes.Cube_fracturepart143_0.geometry} />
        <mesh material={materials['Mat.1']} geometry={nodes.Cube_fracturepart143_1.geometry} />
      </group>
      <group position={[-0.05, 0.78, -0.23]} rotation={[-Math.PI / 2, 0, 0]}>
        <mesh material={materials.Mat} geometry={nodes.Cube_fracturepart144_0.geometry} />
        <mesh material={materials['Mat.1']} geometry={nodes.Cube_fracturepart144_1.geometry} />
      </group>
      <group position={[-0.06, 0.93, -0.07]} rotation={[-Math.PI / 2, 0, 0]}>
        <mesh material={materials.Mat} geometry={nodes.Cube_fracturepart145_0.geometry} />
        <mesh material={materials['Mat.1']} geometry={nodes.Cube_fracturepart145_1.geometry} />
      </group>
      <group position={[0.25, 0.81, -0.03]} rotation={[-Math.PI / 2, 0, 0]}>
        <mesh material={materials.Mat} geometry={nodes.Cube_fracturepart146_0.geometry} />
        <mesh material={materials['Mat.1']} geometry={nodes.Cube_fracturepart146_1.geometry} />
      </group>
      <group position={[0.05, 0.97, -0.09]} rotation={[-Math.PI / 2, 0, 0]}>
        <mesh material={materials.Mat} geometry={nodes.Cube_fracturepart148_0.geometry} />
        <mesh material={materials['Mat.1']} geometry={nodes.Cube_fracturepart148_1.geometry} />
      </group>
      <group position={[0.05, 0.72, 0.29]} rotation={[-Math.PI / 2, 0, 0]}>
        <mesh material={materials.Mat} geometry={nodes.Cube_fracturepart149_0.geometry} />
        <mesh material={materials['Mat.1']} geometry={nodes.Cube_fracturepart149_1.geometry} />
      </group>
      <group position={[0.04, 1.01, 0.03]} rotation={[-Math.PI / 2, 0, 0]}>
        <mesh material={materials.Mat} geometry={nodes.Cube_fracturepart150_0.geometry} />
        <mesh material={materials['Mat.1']} geometry={nodes.Cube_fracturepart150_1.geometry} />
      </group>
      <group position={[-0.15, 0.88, 0.18]} rotation={[-Math.PI / 2, 0, 0]}>
        <mesh material={materials.Mat} geometry={nodes.Cube_fracturepart151_0.geometry} />
        <mesh material={materials['Mat.1']} geometry={nodes.Cube_fracturepart151_1.geometry} />
      </group>
      <group position={[0.25, 0.82, 0.08]} rotation={[-Math.PI / 2, 0, 0]}>
        <mesh material={materials.Mat} geometry={nodes.Cube_fracturepart152_0.geometry} />
        <mesh material={materials['Mat.1']} geometry={nodes.Cube_fracturepart152_1.geometry} />
      </group>
      <group position={[0.19, 0.89, -0.04]} rotation={[-Math.PI / 2, 0, 0]}>
        <mesh material={materials.Mat} geometry={nodes.Cube_fracturepart153_0.geometry} />
        <mesh material={materials['Mat.1']} geometry={nodes.Cube_fracturepart153_1.geometry} />
      </group>
      <group position={[0.02, 0.92, -0.18]} rotation={[-Math.PI / 2, 0, 0]}>
        <mesh material={materials.Mat} geometry={nodes.Cube_fracturepart154_0.geometry} />
        <mesh material={materials['Mat.1']} geometry={nodes.Cube_fracturepart154_1.geometry} />
      </group>
      <group position={[0.18, 0.88, -0.06]} rotation={[-Math.PI / 2, 0, 0]}>
        <mesh material={materials.Mat} geometry={nodes.Cube_fracturepart155_0.geometry} />
        <mesh material={materials['Mat.1']} geometry={nodes.Cube_fracturepart155_1.geometry} />
      </group>
      <group position={[0.05, 0.66, 0.28]} rotation={[-Math.PI / 2, 0, 0]}>
        <mesh material={materials.Mat} geometry={nodes.Cube_fracturepart156_0.geometry} />
        <mesh material={materials['Mat.1']} geometry={nodes.Cube_fracturepart156_1.geometry} />
      </group>
      <group position={[-0.12, 0.89, -0.03]} rotation={[-Math.PI / 2, 0, 0]}>
        <mesh material={materials.Mat} geometry={nodes.Cube_fracturepart157_0.geometry} />
        <mesh material={materials['Mat.1']} geometry={nodes.Cube_fracturepart157_1.geometry} />
      </group>
      <group position={[-0.03, 0.97, -0.1]} rotation={[-Math.PI / 2, 0, 0]}>
        <mesh material={materials.Mat} geometry={nodes.Cube_fracturepart158_0.geometry} />
        <mesh material={materials['Mat.1']} geometry={nodes.Cube_fracturepart158_1.geometry} />
      </group>
      <group position={[-0.17, 0.33, 0.17]} rotation={[-Math.PI / 2, 0, 0]}>
        <mesh material={materials.Mat} geometry={nodes.Cube_fracturepart159_0.geometry} />
        <mesh material={materials['Mat.1']} geometry={nodes.Cube_fracturepart159_1.geometry} />
      </group>
      <group position={[0.25, 0.68, 0.12]} rotation={[-Math.PI / 2, 0, 0]}>
        <mesh material={materials.Mat} geometry={nodes.Cube_fracturepart160_0.geometry} />
        <mesh material={materials['Mat.1']} geometry={nodes.Cube_fracturepart160_1.geometry} />
      </group>
      <group position={[0.02, 0.82, 0.27]} rotation={[-Math.PI / 2, 0, 0]}>
        <mesh material={materials.Mat} geometry={nodes.Cube_fracturepart161_0.geometry} />
        <mesh material={materials['Mat.1']} geometry={nodes.Cube_fracturepart161_1.geometry} />
      </group>
      <group position={[-0.29, 0.56, 0.1]} rotation={[-Math.PI / 2, 0, 0]}>
        <mesh material={materials.Mat} geometry={nodes.Cube_fracturepart162_0.geometry} />
        <mesh material={materials['Mat.1']} geometry={nodes.Cube_fracturepart162_1.geometry} />
      </group>
      <group position={[-0.1, 0.78, -0.13]} rotation={[-Math.PI / 2, 0, 0]}>
        <mesh material={materials.Mat} geometry={nodes.Cube_fracturepart163_0.geometry} />
        <mesh material={materials['Mat.1']} geometry={nodes.Cube_fracturepart163_1.geometry} />
      </group>
      <group position={[0.12, 0.77, 0.18]} rotation={[-Math.PI / 2, 0, 0]}>
        <mesh material={materials.Mat} geometry={nodes.Cube_fracturepart164_0.geometry} />
        <mesh material={materials['Mat.1']} geometry={nodes.Cube_fracturepart164_1.geometry} />
      </group>
      <group position={[0.18, 0.73, 0.18]} rotation={[-Math.PI / 2, 0, 0]}>
        <mesh material={materials.Mat} geometry={nodes.Cube_fracturepart165_0.geometry} />
        <mesh material={materials['Mat.1']} geometry={nodes.Cube_fracturepart165_1.geometry} />
      </group>
      <group position={[-0.28, 0.75, 0.1]} rotation={[-Math.PI / 2, 0, 0]}>
        <mesh material={materials.Mat} geometry={nodes.Cube_fracturepart166_0.geometry} />
        <mesh material={materials['Mat.1']} geometry={nodes.Cube_fracturepart166_1.geometry} />
      </group>
      <group position={[0.09, 0.93, 0.02]} rotation={[-Math.PI / 2, 0, 0]}>
        <mesh material={materials.Mat} geometry={nodes.Cube_fracturepart167_0.geometry} />
        <mesh material={materials['Mat.1']} geometry={nodes.Cube_fracturepart167_1.geometry} />
      </group>
      <group position={[-0.24, 0.77, 0]} rotation={[-Math.PI / 2, 0, 0]}>
        <mesh material={materials.Mat} geometry={nodes.Cube_fracturepart168_0.geometry} />
        <mesh material={materials['Mat.1']} geometry={nodes.Cube_fracturepart168_1.geometry} />
      </group>
      <group position={[0.06, 0.98, 0.06]} rotation={[-Math.PI / 2, 0, 0]}>
        <mesh material={materials.Mat} geometry={nodes.Cube_fracturepart169_0.geometry} />
        <mesh material={materials['Mat.1']} geometry={nodes.Cube_fracturepart169_1.geometry} />
      </group>
      <group position={[0.03, 0.89, 0.26]} rotation={[-Math.PI / 2, 0, 0]}>
        <mesh material={materials.Mat} geometry={nodes.Cube_fracturepart170_0.geometry} />
        <mesh material={materials['Mat.1']} geometry={nodes.Cube_fracturepart170_1.geometry} />
      </group>
      <group position={[-0.23, 0.63, -0.14]} rotation={[-Math.PI / 2, 0, 0]}>
        <mesh material={materials.Mat} geometry={nodes.Cube_fracturepart172_0.geometry} />
        <mesh material={materials['Mat.1']} geometry={nodes.Cube_fracturepart172_1.geometry} />
      </group>
      <group position={[0.24, 0.32, 0]} rotation={[-Math.PI / 2, 0, 0]}>
        <mesh material={materials.Mat} geometry={nodes.Cube_fracturepart173_0.geometry} />
        <mesh material={materials['Mat.1']} geometry={nodes.Cube_fracturepart173_1.geometry} />
      </group>
      <group position={[0, 0.93, 0.16]} rotation={[-Math.PI / 2, 0, 0]}>
        <mesh material={materials.Mat} geometry={nodes.Cube_fracturepart174_0.geometry} />
        <mesh material={materials['Mat.1']} geometry={nodes.Cube_fracturepart174_1.geometry} />
      </group>
      <group position={[0.22, 0.88, 0.08]} rotation={[-Math.PI / 2, 0, 0]}>
        <mesh material={materials.Mat} geometry={nodes.Cube_fracturepart176_0.geometry} />
        <mesh material={materials['Mat.1']} geometry={nodes.Cube_fracturepart176_1.geometry} />
      </group>
      <group position={[0.01, 0.28, 0.15]} rotation={[-Math.PI / 2, 0, 0]}>
        <mesh material={materials.Mat} geometry={nodes.Cube_fracturepart177_0.geometry} />
        <mesh material={materials['Mat.1']} geometry={nodes.Cube_fracturepart177_1.geometry} />
      </group>
      <group position={[0.08, 0.95, -0.12]} rotation={[-Math.PI / 2, 0, 0]}>
        <mesh material={materials.Mat} geometry={nodes.Cube_fracturepart179_0.geometry} />
        <mesh material={materials['Mat.1']} geometry={nodes.Cube_fracturepart179_1.geometry} />
      </group>
      <group position={[0.2, 0.44, 0.16]} rotation={[-Math.PI / 2, 0, 0]}>
        <mesh material={materials.Mat} geometry={nodes.Cube_fracturepart180_0.geometry} />
        <mesh material={materials['Mat.1']} geometry={nodes.Cube_fracturepart180_1.geometry} />
      </group>
      <group position={[-0.15, 0.72, -0.19]} rotation={[-Math.PI / 2, 0, 0]}>
        <mesh material={materials.Mat} geometry={nodes.Cube_fracturepart182_0.geometry} />
        <mesh material={materials['Mat.1']} geometry={nodes.Cube_fracturepart182_1.geometry} />
      </group>
      <group position={[0.19, 0.34, 0.22]} rotation={[-Math.PI / 2, 0, 0]}>
        <mesh material={materials.Mat} geometry={nodes.Cube_fracturepart183_0.geometry} />
        <mesh material={materials['Mat.1']} geometry={nodes.Cube_fracturepart183_1.geometry} />
      </group>
      <group position={[-0.18, 0.76, -0.07]} rotation={[-Math.PI / 2, 0, 0]}>
        <mesh material={materials.Mat} geometry={nodes.Cube_fracturepart184_0.geometry} />
        <mesh material={materials['Mat.1']} geometry={nodes.Cube_fracturepart184_1.geometry} />
      </group>
      <group position={[0.09, 0.28, -0.18]} rotation={[-Math.PI / 2, 0, 0]}>
        <mesh material={materials.Mat} geometry={nodes.Cube_fracturepart185_0.geometry} />
        <mesh material={materials['Mat.1']} geometry={nodes.Cube_fracturepart185_1.geometry} />
      </group>
      <group position={[-0.11, 0.89, 0.06]} rotation={[-Math.PI / 2, 0, 0]}>
        <mesh material={materials.Mat} geometry={nodes.Cube_fracturepart186_0.geometry} />
        <mesh material={materials['Mat.1']} geometry={nodes.Cube_fracturepart186_1.geometry} />
      </group>
      <group position={[0.12, 0.73, 0.27]} rotation={[-Math.PI / 2, 0, 0]}>
        <mesh material={materials.Mat} geometry={nodes.Cube_fracturepart187_0.geometry} />
        <mesh material={materials['Mat.1']} geometry={nodes.Cube_fracturepart187_1.geometry} />
      </group>
      <group position={[0.06, 0.81, -0.14]} rotation={[-Math.PI / 2, 0, 0]}>
        <mesh material={materials.Mat} geometry={nodes.Cube_fracturepart189_0.geometry} />
        <mesh material={materials['Mat.1']} geometry={nodes.Cube_fracturepart189_1.geometry} />
      </group>
      <group position={[0.16, 0.6, 0.22]} rotation={[-Math.PI / 2, 0, 0]}>
        <mesh material={materials.Mat} geometry={nodes.Cube_fracturepart190_0.geometry} />
        <mesh material={materials['Mat.1']} geometry={nodes.Cube_fracturepart190_1.geometry} />
      </group>
      <group position={[-0.29, 0.64, -0.04]} rotation={[-Math.PI / 2, 0, 0]}>
        <mesh material={materials.Mat} geometry={nodes.Cube_fracturepart191_0.geometry} />
        <mesh material={materials['Mat.1']} geometry={nodes.Cube_fracturepart191_1.geometry} />
      </group>
      <group position={[0.29, 0.51, 0.05]} rotation={[-Math.PI / 2, 0, 0]}>
        <mesh material={materials.Mat} geometry={nodes.Cube_fracturepart192_0.geometry} />
        <mesh material={materials['Mat.1']} geometry={nodes.Cube_fracturepart192_1.geometry} />
      </group>
      <group position={[0.15, 0.94, -0.05]} rotation={[-Math.PI / 2, 0, 0]}>
        <mesh material={materials.Mat} geometry={nodes.Cube_fracturepart193_0.geometry} />
        <mesh material={materials['Mat.1']} geometry={nodes.Cube_fracturepart193_1.geometry} />
      </group>
      <group position={[-0.02, 0.92, -0.15]} rotation={[-Math.PI / 2, 0, 0]}>
        <mesh material={materials.Mat} geometry={nodes.Cube_fracturepart194_0.geometry} />
        <mesh material={materials['Mat.1']} geometry={nodes.Cube_fracturepart194_1.geometry} />
      </group>
      <group position={[0.06, 0.89, 0.24]} rotation={[-Math.PI / 2, 0, 0]}>
        <mesh material={materials.Mat} geometry={nodes.Cube_fracturepart195_0.geometry} />
        <mesh material={materials['Mat.1']} geometry={nodes.Cube_fracturepart195_1.geometry} />
      </group>
      <group position={[-0.03, 0.96, -0.01]} rotation={[-Math.PI / 2, 0, 0]}>
        <mesh material={materials.Mat} geometry={nodes.Cube_fracturepart196_0.geometry} />
        <mesh material={materials['Mat.1']} geometry={nodes.Cube_fracturepart196_1.geometry} />
      </group>
      <group position={[0.09, 0.9, -0.07]} rotation={[-Math.PI / 2, 0, 0]}>
        <mesh material={materials.Mat} geometry={nodes.Cube_fracturepart197_0.geometry} />
        <mesh material={materials['Mat.1']} geometry={nodes.Cube_fracturepart197_1.geometry} />
      </group>
      <group position={[0.16, 0.84, 0.22]} rotation={[-Math.PI / 2, 0, 0]}>
        <mesh material={materials.Mat} geometry={nodes.Cube_fracturepart198_0.geometry} />
        <mesh material={materials['Mat.1']} geometry={nodes.Cube_fracturepart198_1.geometry} />
      </group>
      <group position={[-0.22, 0.68, -0.01]} rotation={[-Math.PI / 2, 0, 0]}>
        <mesh material={materials.Mat} geometry={nodes.Cube_fracturepart199_0.geometry} />
        <mesh material={materials['Mat.1']} geometry={nodes.Cube_fracturepart199_1.geometry} />
      </group>
      <group position={[-0.14, 0.52, -0.25]} rotation={[-Math.PI / 2, 0, 0]}>
        <mesh material={materials.Mat} geometry={nodes.Cube_fracturepart201_0.geometry} />
        <mesh material={materials['Mat.1']} geometry={nodes.Cube_fracturepart201_1.geometry} />
      </group>
      <group position={[-0.03, 0.59, -0.27]} rotation={[-Math.PI / 2, 0, 0]}>
        <mesh material={materials.Mat} geometry={nodes.Cube_fracturepart202_0.geometry} />
        <mesh material={materials['Mat.1']} geometry={nodes.Cube_fracturepart202_1.geometry} />
      </group>
      <group position={[-0.09, 0.49, 0.32]} rotation={[-Math.PI / 2, 0, 0]}>
        <mesh material={materials.Mat} geometry={nodes.Cube_fracturepart203_0.geometry} />
        <mesh material={materials['Mat.1']} geometry={nodes.Cube_fracturepart203_1.geometry} />
      </group>
      <group position={[-0.13, 0.91, -0.12]} rotation={[-Math.PI / 2, 0, 0]}>
        <mesh material={materials.Mat} geometry={nodes.Cube_fracturepart204_0.geometry} />
        <mesh material={materials['Mat.1']} geometry={nodes.Cube_fracturepart204_1.geometry} />
      </group>
      <group position={[-0.06, 0.68, -0.24]} rotation={[-Math.PI / 2, 0, 0]}>
        <mesh material={materials.Mat} geometry={nodes.Cube_fracturepart205_0.geometry} />
        <mesh material={materials['Mat.1']} geometry={nodes.Cube_fracturepart205_1.geometry} />
      </group>
      <group position={[-0.01, 0.83, -0.14]} rotation={[-Math.PI / 2, 0, 0]}>
        <mesh material={materials.Mat} geometry={nodes.Cube_fracturepart206_0.geometry} />
        <mesh material={materials['Mat.1']} geometry={nodes.Cube_fracturepart206_1.geometry} />
      </group>
    </group>
  )
}
